version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.1.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - qdrant_network

  embedding_service:
    build:
      context: .
      dockerfile: Dockerfile.embedding_service
    ports:
      - "5001:5001"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    depends_on:
      - qdrant
    networks:
      - qdrant_network

  book_parser:
    build:
      context: .
      dockerfile: Dockerfile.book_parser
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - EMBEDDING_SERVICE_URL=http://embedding_service:5001
    depends_on:
      - qdrant
      - embedding_service
    networks:
      - qdrant_network

volumes:
  qdrant_data:

networks:
  qdrant_network: